version: "2"

volumes:
  phyLinux-home:

services:
  autodoc:
    restart: "no"

    image: ldericher/autodoc
    build:
      context: ./build

    command: "bash"

    volumes:
      - "${PWD}/example_docs:/docs"
      - "${PWD}/build/autodoc:/usr/local/bin/autodoc:ro"
