version: "2"

volumes:
  phyLinux-home:

services:
  autodoc:
    restart: "no"

    image: ldericher/autodoc
    build:
      context: ./build

    volumes:
      - "${PWD}/build/autodoc.sh:/usr/local/bin/autodoc:ro"
      - "${PWD}/example_docs:/docs"
