version: "2"

volumes:
  phyLinux-home:

services:
  autodoc:
    restart: "no"

    image: ldericher/autodoc
    build:
      context: ./build

    command: "bash"

    volumes:
      - "${PWD}/build/usr/local/bin/autodoc:/usr/local/bin/autodoc:ro"
      - "${PWD}/build/usr/local/lib/autodoc:/usr/local/lib/autodoc:ro"
      - "${PWD}/examples:/docs"
