version: "2"

volumes:
  phyLinux-home:

services:
  autodoc:
    restart: "no"

    image: ldericher/autodoc
    build:
      context: ./src

    command: "bash"

    volumes:
      - "${PWD}/src/usr/local/bin/autodoc:/usr/local/bin/autodoc:ro"
      - "${PWD}/src/usr/local/lib/autodoc:/usr/local/lib/autodoc:ro"
      - "${PWD}/examples:/docs"
